### ISSUE TITLE
Move everything up one folder, so build.gradle is at root

### ISSUE THREAD

**Issue by maael** [CompSciLabs/my-playlist-alarm#1]
It seems this is standard, and makes it easier to work with the project straight away in Android Studio.

**Comment by Johnbastian** [comment]
+1

**Comment by Johnbastian** [comment]
@bennyboy23 @clownyXD

**Comment by Johnbastian** [comment]
Done in commit 5d0826563fe2d799aef458eb5bbd6293ddc16bc5
